# Generated by Django 3.2.16 on 2023-12-13 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='班级名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='ClazzStudents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='课程名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('major_code', models.CharField(max_length=32, unique=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='专业名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTimeTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clazz_week', models.CharField(choices=[(1, '8:00~9:40'), (2, '10:00~11:40'), (3, '14:00~15:40'), (4, '15:50~17:50')], max_length=32, verbose_name='周几的课')),
                ('clazz_time', models.CharField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五')], max_length=32, verbose_name='上课时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clazz')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.curriculum')),
            ],
        ),
    ]
