# Generated by Django 3.2.16 on 2023-12-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo'),
        ),
        migrations.AddField(
            model_name='clazzstudents',
            name='clazz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clazz'),
        ),
        migrations.AddField(
            model_name='clazzstudents',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo'),
        ),
        migrations.AddField(
            model_name='clazz',
            name='major_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.major'),
        ),
        migrations.AlterUniqueTogether(
            name='schooltimetable',
            unique_together={('clazz_week', 'clazz_time', 'clazz_id')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'teacher_id')},
        ),
        migrations.AlterUniqueTogether(
            name='clazzstudents',
            unique_together={('student_id', 'clazz_id')},
        ),
    ]
