# Generated by Django 3.2.16 on 2023-12-19 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('manager', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCurriculumScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('curriculum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.curriculum')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'unique_together': {('student_id', 'curriculum_id')},
            },
        ),
    ]
