# Generated by Django 3.2.16 on 2023-12-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_type',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'teacher')], default=0, verbose_name='账号类型'),
        ),
    ]
