# Generated by Django 3.2.16 on 2023-12-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_type',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'teacher'), (2, 'manager')], default=0, verbose_name='账号类型'),
        ),
    ]
